name: Release Notification

on:
  release:
    types: [created]
  workflow_dispatch: # This allows for manual triggering

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    steps:
      - name: Notify Slack on Releases
        uses: amendx/slackbot-release@1.0.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
